package com.liferay.docs.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Worker service. Represents a row in the &quot;Event_Worker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.servicebuilder.model.impl.WorkerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.servicebuilder.model.impl.WorkerImpl}.
 * </p>
 *
 * @author gerbe
 * @see Worker
 * @see com.liferay.docs.servicebuilder.model.impl.WorkerImpl
 * @see com.liferay.docs.servicebuilder.model.impl.WorkerModelImpl
 * @generated
 */
public interface WorkerModel extends BaseModel<Worker> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a worker model instance should use the {@link Worker} interface instead.
     */

    /**
     * Returns the primary key of this worker.
     *
     * @return the primary key of this worker
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this worker.
     *
     * @param primaryKey the primary key of this worker
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the worker ID of this worker.
     *
     * @return the worker ID of this worker
     */
    public long getWorkerId();

    /**
     * Sets the worker ID of this worker.
     *
     * @param workerId the worker ID of this worker
     */
    public void setWorkerId(long workerId);

    /**
     * Returns the first name of this worker.
     *
     * @return the first name of this worker
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this worker.
     *
     * @param firstName the first name of this worker
     */
    public void setFirstName(String firstName);

    /**
     * Returns the middle name of this worker.
     *
     * @return the middle name of this worker
     */
    @AutoEscape
    public String getMiddleName();

    /**
     * Sets the middle name of this worker.
     *
     * @param middleName the middle name of this worker
     */
    public void setMiddleName(String middleName);

    /**
     * Returns the last name of this worker.
     *
     * @return the last name of this worker
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this worker.
     *
     * @param lastName the last name of this worker
     */
    public void setLastName(String lastName);

    /**
     * Returns the gender of this worker.
     *
     * @return the gender of this worker
     */
    @AutoEscape
    public String getGender();

    /**
     * Sets the gender of this worker.
     *
     * @param gender the gender of this worker
     */
    public void setGender(String gender);

    /**
     * Returns the date of birth of this worker.
     *
     * @return the date of birth of this worker
     */
    @AutoEscape
    public String getDateOfBirth();

    /**
     * Sets the date of birth of this worker.
     *
     * @param dateOfBirth the date of birth of this worker
     */
    public void setDateOfBirth(String dateOfBirth);

    /**
     * Returns the position ID of this worker.
     *
     * @return the position ID of this worker
     */
    public long getPositionId();

    /**
     * Sets the position ID of this worker.
     *
     * @param positionId the position ID of this worker
     */
    public void setPositionId(long positionId);

    /**
     * Returns the employment date of this worker.
     *
     * @return the employment date of this worker
     */
    @AutoEscape
    public String getEmploymentDate();

    /**
     * Sets the employment date of this worker.
     *
     * @param employmentDate the employment date of this worker
     */
    public void setEmploymentDate(String employmentDate);

    /**
     * Returns the salary level of this worker.
     *
     * @return the salary level of this worker
     */
    @AutoEscape
    public String getSalaryLevel();

    /**
     * Sets the salary level of this worker.
     *
     * @param salaryLevel the salary level of this worker
     */
    public void setSalaryLevel(String salaryLevel);

    /**
     * Returns the number work phone of this worker.
     *
     * @return the number work phone of this worker
     */
    @AutoEscape
    public String getNumberWorkPhone();

    /**
     * Sets the number work phone of this worker.
     *
     * @param numberWorkPhone the number work phone of this worker
     */
    public void setNumberWorkPhone(String numberWorkPhone);

    /**
     * Returns the number home phone of this worker.
     *
     * @return the number home phone of this worker
     */
    @AutoEscape
    public String getNumberHomePhone();

    /**
     * Sets the number home phone of this worker.
     *
     * @param numberHomePhone the number home phone of this worker
     */
    public void setNumberHomePhone(String numberHomePhone);

    /**
     * Returns the bank ID of this worker.
     *
     * @return the bank ID of this worker
     */
    public long getBankId();

    /**
     * Sets the bank ID of this worker.
     *
     * @param bankId the bank ID of this worker
     */
    public void setBankId(long bankId);

    /**
     * Returns the archived of this worker.
     *
     * @return the archived of this worker
     */
    public boolean getArchived();

    /**
     * Returns <code>true</code> if this worker is archived.
     *
     * @return <code>true</code> if this worker is archived; <code>false</code> otherwise
     */
    public boolean isArchived();

    /**
     * Sets whether this worker is archived.
     *
     * @param archived the archived of this worker
     */
    public void setArchived(boolean archived);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.liferay.docs.servicebuilder.model.Worker worker);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.docs.servicebuilder.model.Worker> toCacheModel();

    @Override
    public com.liferay.docs.servicebuilder.model.Worker toEscapedModel();

    @Override
    public com.liferay.docs.servicebuilder.model.Worker toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
